### ISSUE TITLE
Navigation Issue

### ISSUE THREAD

**Issue by KhilanVitthani** [YudizAndroidKishan/flutter_dino#1]
I found an issue with the navigation. When the internet is off and the user opens the app, the No-internet screen is open, but the splash screen also works in the background, so when the splash screen navigates to another screen, the internet screen is gone.

https://github.com/user-attachments/assets/733664d9-f3af-4d20-8d17-29828b533671

**Comment by YudizAndroidKishan** [comment]
fixed this issue in version 1.0.1+2

**Comment by KhilanVitthani** [comment]
Still having same issue with latest version

**Comment by YudizAndroidKishan** [comment]
Could you please provide me steps to reproduce this issue and it would be grate if you provide me code snippet of you implementation

**Comment by KhilanVitthani** [comment]
```
  await FlutterDino.initialize(
    config: FlutterDinoConfig(
      navigatorKey: navigatorKey,
    ),
  );
```
  
I added this code in my main.dart file and the initial page is the splash screen on init of a splash; I run the timer for 2 seconds, then navigate to other screens

**Comment by YudizAndroidKishan** [comment]
@KhilanVitthani Here is the full implementation 

```
import 'package:flutter/material.dart';
import 'package:flutter_dino/flutter_dino.dart';

void main() async {
  final navigatorKey = GlobalKey<NavigatorState>();
  
  WidgetsFlutterBinding.ensureInitialized();
  
  await FlutterDino.initialize(
    config: FlutterDinoConfig(
      navigatorKey: navigatorKey,
    ),
  );
  
  runApp(
    MaterialApp(
      navigatorKey: navigatorKey,
      home: HomePage(),
      navigatorObservers: [
        FlutterDino.instance.navigatorObserver, // do not forget to add this 
      ],
    ),
  );
}
```

**Comment by KhilanVitthani** [comment]
`Restarted application in 7,773ms.
I/flutter (14453): systemDefaultLocale: en
D/EGL_emulation(14453): app_time_stats: avg=24859.98ms min=24859.98ms max=24859.98ms count=1
E/flutter (14453): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (14453): #0      DialogServices.showCustomDialog (package:flutter_dino/services/dialog_services.dart:32:51)
E/flutter (14453): #1      DialogServices.showNoInternetDialog (package:flutter_dino/services/dialog_services.dart:40:11)
E/flutter (14453): #2      FlutterDino._handleConnectivityChange (package:flutter_dino/services/flutter_dino.dart:102:31)
E/flutter (14453): #3      FlutterDino._checkInitialConnectivity (package:flutter_dino/services/flutter_dino.dart:79:5)
E/flutter (14453): <asynchronous suspension>
E/flutter (14453): 
`

when internet is not connected and run app it give error

**Comment by YudizAndroidKishan** [comment]
@KhilanVitthani Could you please share output of 
```flutter doctor -v```

**Comment by KhilanVitthani** [comment]
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.5 23F79 darwin-x64, locale en-US)
    • Flutter version 3.24.3 on channel stable at /Users/imac/developer/flutter_3_16_9
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (9 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/imac/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)

[✓] Connected device (5 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554                            • android-x64    • Android 14 (API 34) (emulator)
    • macOS (desktop)              • macos                                    • darwin-x64     • macOS 14.5 23F79 darwin-x64
    • Chrome (web)                 • chrome                                   • web-javascript • Google Chrome 130.0.6723.117
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by YudizAndroidKishan** [comment]
First of all thankyou @KhilanVitthani  for providing me a good insight on the issue 
i am trying to reproduce this issue meanwhile could you please try in real device :)

**Comment by KhilanVitthani** [comment]
i also try in real device but still facing same issue

**Comment by YudizAndroidKishan** [comment]
Dear @KhilanVitthani i have fixed the issue please check version 1.0.1+3 and do let me know :)
and thanks supporting ❤️

**Comment by KhilanVitthani** [comment]
Thank's it is working now.

**Comment by YudizAndroidKishan** [comment]
Thanks @KhilanVitthani for your valuable insight
